# Generated by Django 4.1.3 on 2023-05-30 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="image",
            field=models.ImageField(
                default="intruder_image/default_error.png",
                upload_to="intruder_image/%Y/%m/%d/",
            ),
        ),
    ]
