# Generated by Django 4.1.3 on 2023-05-30 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_post_image"),
    ]

    operations = [
        migrations.RemoveField(model_name="post", name="author",),
    ]
